import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class uiInfo(object):
    def setup_ui(self, info):
        info.setObjectName("Info")
        info.resize(605, 950)
        self.centralwidget = QtWidgets.QWidget(info)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(41, 11, 528, 884))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.coordinates_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.coordinates_label.setFont(font)
        self.coordinates_label.setAlignment(QtCore.Qt.AlignCenter)
        self.coordinates_label.setObjectName("coordinates_label")
        self.gridLayout.addWidget(self.coordinates_label, 9, 0, 1, 3)

        self.memory_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.memory_label.setFont(font)
        self.memory_label.setAlignment(QtCore.Qt.AlignCenter)
        self.memory_label.setObjectName("memory_label")
        self.gridLayout.addWidget(self.memory_label, 4, 0, 1, 1)

        self.frequencies_text = QtWidgets.QTextBrowser(self.layoutWidget)
        self.frequencies_text.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.frequencies_text.setFont(font)
        self.frequencies_text.setObjectName("frequencies_text")
        self.gridLayout.addWidget(self.frequencies_text, 15, 0, 1, 3)

        self.multiplicity_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.multiplicity_label.setFont(font)
        self.multiplicity_label.setAlignment(QtCore.Qt.AlignCenter)
        self.multiplicity_label.setObjectName("multiplicity_label")
        self.gridLayout.addWidget(self.multiplicity_label, 8, 0, 1, 1)

        self.coordinates_text = QtWidgets.QTextBrowser(self.layoutWidget)
        self.coordinates_text.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.coordinates_text.setFont(font)
        self.coordinates_text.setObjectName("coordinates_text")
        self.gridLayout.addWidget(self.coordinates_text, 10, 0, 1, 3)

        self.memory_text = QtWidgets.QTextBrowser(self.layoutWidget)
        self.memory_text.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.memory_text.setFont(font)
        self.memory_text.setObjectName("memory_text")
        self.gridLayout.addWidget(self.memory_text, 4, 1, 1, 2)

        self.opt_text = QtWidgets.QTextBrowser(self.layoutWidget)
        self.opt_text.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.opt_text.setFont(font)
        self.opt_text.setObjectName("opt_text")
        self.gridLayout.addWidget(self.opt_text, 17, 0, 1, 3)

        self.energy_label = QtWidgets.QLabel(self.layoutWidget)
        self.energy_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.energy_label.setFont(font)
        self.energy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.energy_label.setObjectName("energy_label")
        self.gridLayout.addWidget(self.energy_label, 11, 0, 1, 1)

        self.simulation_label = QtWidgets.QLabel(self.layoutWidget)
        self.simulation_label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.simulation_label.setFont(font)
        self.simulation_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.simulation_label.setAutoFillBackground(False)
        self.simulation_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.simulation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.simulation_label.setObjectName("simulation_label")
        self.gridLayout.addWidget(self.simulation_label, 2, 0, 1, 3)

        self.quote_text = QtWidgets.QTextBrowser(self.layoutWidget)
        self.quote_text.setMinimumSize(QtCore.QSize(0, 0))
        self.quote_text.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setItalic(True)
        self.quote_text.setFont(font)
        self.quote_text.setObjectName("quote_text")
        self.gridLayout.addWidget(self.quote_text, 1, 0, 1, 3)

        self.comment_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.comment_label.setFont(font)
        self.comment_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comment_label.setObjectName("comment_label")
        self.gridLayout.addWidget(self.comment_label, 6, 0, 1, 1)

        self.options_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.options_label.setFont(font)
        self.options_label.setAlignment(QtCore.Qt.AlignCenter)
        self.options_label.setObjectName("options_label")
        self.gridLayout.addWidget(self.options_label, 5, 0, 1, 1)

        self.quote_label = QtWidgets.QLabel(self.layoutWidget)
        self.quote_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.quote_label.setFont(font)
        self.quote_label.setAlignment(QtCore.Qt.AlignCenter)
        self.quote_label.setObjectName("quote_label")
        self.gridLayout.addWidget(self.quote_label, 0, 0, 1, 3)

        self.charge_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.charge_label.setFont(font)
        self.charge_label.setAlignment(QtCore.Qt.AlignCenter)
        self.charge_label.setObjectName("charge_label")
        self.gridLayout.addWidget(self.charge_label, 7, 0, 1, 1)

        self.frequencies_label = QtWidgets.QLabel(self.layoutWidget)
        self.frequencies_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.frequencies_label.setFont(font)
        self.frequencies_label.setAlignment(QtCore.Qt.AlignCenter)
        self.frequencies_label.setObjectName("frequencies_label")
        self.gridLayout.addWidget(self.frequencies_label, 14, 0, 1, 3)

        self.thermochemistry_label = QtWidgets.QLabel(self.layoutWidget)
        self.thermochemistry_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.thermochemistry_label.setFont(font)
        self.thermochemistry_label.setAlignment(QtCore.Qt.AlignCenter)
        self.thermochemistry_label.setObjectName("thermochemistry_label")
        self.gridLayout.addWidget(self.thermochemistry_label, 12, 0, 1, 3)

        self.multiplicity_text = QtWidgets.QTextBrowser(self.layoutWidget)
        self.multiplicity_text.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.multiplicity_text.setFont(font)
        self.multiplicity_text.setObjectName("multiplicity_text")
        self.gridLayout.addWidget(self.multiplicity_text, 8, 1, 1, 2)

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 18, 0, 1, 3)

        self.checkpoint_text = QtWidgets.QTextBrowser(self.layoutWidget)
        self.checkpoint_text.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.checkpoint_text.setFont(font)
        self.checkpoint_text.setObjectName("checkpoint_text")
        self.gridLayout.addWidget(self.checkpoint_text, 3, 1, 1, 2)

        self.options_text = QtWidgets.QTextBrowser(self.layoutWidget)
        self.options_text.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.options_text.setFont(font)
        self.options_text.setObjectName("options_text")
        self.gridLayout.addWidget(self.options_text, 5, 1, 1, 2)

        self.checkpoint_label = QtWidgets.QLabel(self.layoutWidget)
        self.checkpoint_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.checkpoint_label.setFont(font)
        self.checkpoint_label.setAlignment(QtCore.Qt.AlignCenter)
        self.checkpoint_label.setObjectName("checkpoint_label")
        self.gridLayout.addWidget(self.checkpoint_label, 3, 0, 1, 1)

        self.thermochemistry_text = QtWidgets.QTextBrowser(self.layoutWidget)
        self.thermochemistry_text.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.thermochemistry_text.setFont(font)
        self.thermochemistry_text.setObjectName("thermochemistry_text")
        self.gridLayout.addWidget(self.thermochemistry_text, 13, 0, 1, 3)

        self.charge_text = QtWidgets.QTextBrowser(self.layoutWidget)
        self.charge_text.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.charge_text.setFont(font)
        self.charge_text.setObjectName("charge_text")
        self.gridLayout.addWidget(self.charge_text, 7, 1, 1, 2)

        self.comment_text = QtWidgets.QTextBrowser(self.layoutWidget)
        self.comment_text.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.comment_text.setFont(font)
        self.comment_text.setObjectName("comment_text")
        self.gridLayout.addWidget(self.comment_text, 6, 1, 1, 2)

        self.energy_text = QtWidgets.QTextBrowser(self.layoutWidget)
        self.energy_text.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.energy_text.setFont(font)
        self.energy_text.setObjectName("energy_text")
        self.gridLayout.addWidget(self.energy_text, 11, 1, 1, 2)

        self.opt_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.opt_label.setFont(font)
        self.opt_label.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label.setObjectName("opt_label")
        self.gridLayout.addWidget(self.opt_label, 16, 0, 1, 3)

        info.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(info)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 605, 21))
        self.menubar.setObjectName("menubar")
        info.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(info)
        self.statusbar.setObjectName("statusbar")
        info.setStatusBar(self.statusbar)

        self.translate_ui(info)
        QtCore.QMetaObject.connectSlotsByName(info)

    def translate_ui(self, info):
        _translate = QtCore.QCoreApplication.translate
        info.setWindowTitle(_translate("Info", "MainWindow"))
        self.coordinates_label.setText(_translate("Info", "Provided coordinates"))
        self.memory_label.setText(_translate("Info", "Memory used"))
        self.multiplicity_label.setText(_translate("Info", "Multiplicity"))
        self.energy_label.setText(_translate("Info", "Energy of molecule"))
        self.simulation_label.setText(_translate("Info", "Simulation settings"))
        self.comment_label.setText(_translate("Info", "Comment"))
        self.options_label.setText(_translate("Info", "Options"))
        self.quote_label.setText(_translate("Info", "Not so inspirational quote"))
        self.charge_label.setText(_translate("Info", "Charge"))
        self.frequencies_label.setText(_translate("Info", "Frequencies"))
        self.thermochemistry_label.setText(_translate("Info", "Thermochemistry"))
        self.checkpoint_label.setText(_translate("Info", "Checkpoint file"))
        self.opt_label.setText(_translate("Info", "Optimized coordinates"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Info = QtWidgets.QMainWindow()
    ui = uiInfo()
    ui.setup_ui(Info)
    Info.show()
    sys.exit(app.exec_())
